const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function toast(t='복사 완료!'){let e=$('.toast');if(!e){e=document.createElement('div');e.className='toast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1500)}
async function copyText(t){try{await navigator.clipboard.writeText(t);return true}catch(e){const ta=document.createElement('textarea');ta.value=t;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();return ok}}
async function shareResult(title,text){const data={title,text,url:location.href};try{if(navigator.share){await navigator.share(data)}else{await copyText(`${title}\n${text}\n${location.href}`);toast('결과 링크 복사 완료 ✨')}}catch(e){}}
async function copyResult(text){await copyText(`${text}\n${location.href}`);toast('복사 완료 ✨')}
function randPercent(min=41,max=99){return Math.floor(Math.random()*(max-min+1))+min}
function showResult(el){el.classList.remove('show');void el.offsetWidth;el.classList.add('show')}
function wrapCanvasText(ctx,text,x,y,maxWidth,lineHeight,maxLines=6){const words=text.split(' ');let line='',lines=0;for(let n=0;n<words.length;n++){const test=line+words[n]+' ';if(ctx.measureText(test).width>maxWidth&&n>0){ctx.fillText(line.trim(),x,y);line=words[n]+' ';y+=lineHeight;if(++lines>=maxLines)return y}else line=test}ctx.fillText(line.trim(),x,y);return y+lineHeight}
async function downloadResultCard(title,body,imgSrc=''){const c=document.createElement('canvas');c.width=1080;c.height=1350;const ctx=c.getContext('2d'),g=ctx.createLinearGradient(0,0,1080,1350);g.addColorStop(0,'#171327');g.addColorStop(.5,'#3a2853');g.addColorStop(1,'#8a4266');ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='rgba(255,255,255,.08)';ctx.beginPath();ctx.roundRect(70,70,940,1210,48);ctx.fill();ctx.fillStyle='#c9b5ff';ctx.font='700 34px sans-serif';ctx.fillText('HEARTVERSE · RESULT',115,145);let textY=245;if(imgSrc){try{const im=new Image();im.src=imgSrc;await im.decode();const ratio=Math.min(500/im.width,560/im.height);const w=im.width*ratio,h=im.height*ratio;ctx.drawImage(im,(1080-w)/2,190,w,h);textY=190+h+65}catch(e){}}ctx.fillStyle='#fff';ctx.font='900 58px sans-serif';textY=wrapCanvasText(ctx,title,115,textY,850,72,3)+20;ctx.fillStyle='#e2deea';ctx.font='400 34px sans-serif';wrapCanvasText(ctx,body,115,textY,850,52,7);ctx.fillStyle='#b8aec5';ctx.font='500 26px sans-serif';ctx.fillText('친구한테 보내고 “너는 뭐 나옴?” 물어보기',115,1190);ctx.fillText('son-8oh.pages.dev',115,1240);const a=document.createElement('a');a.download='heartverse-result.png';a.href=c.toDataURL('image/png');a.click();toast('스토리용 결과 카드 저장 완료 📸')}

const MOBILE_TESTS=[['💌','캐릭터상','character.html'],['💬','썸 온도','crush.html'],['👯','취향 궁합','friendmatch.html'],['✨','최애캐','bias.html'],['🚨','취향 위험도','danger.html'],['🎟️','데이트','dateworld.html'],['🎧','최애 멘트','ment.html']];
function currentFile(){const p=location.pathname.split('/').pop();return p||'index.html'}
function applyBranding(){document.title=document.title.replaceAll('오늘뭐함','Heartverse');const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{const p=n.parentElement;if(!p||['SCRIPT','STYLE'].includes(p.tagName))return;if(n.nodeValue.includes('오늘뭐함'))n.nodeValue=n.nodeValue.replaceAll('오늘뭐함','Heartverse')})}
function fixCharacterArt(){const apply=()=>{$$('.hero-character img,.character-stage img,.result img,.result-card img').forEach(img=>{img.style.mixBlendMode='normal';img.style.background='transparent';img.style.borderRadius='20px';img.style.maxWidth='100%';img.style.objectFit='contain';img.style.filter='none'})};apply();const observer=new MutationObserver(apply);observer.observe(document.body,{subtree:true,attributes:true,attributeFilter:['src']})}
function initMobileNavigation(){const current=currentFile(),allowed=['index.html',...MOBILE_TESTS.map(x=>x[2])];if(!allowed.includes(current))return;document.body.classList.add('has-mobile-dock');const dock=document.createElement('nav');dock.className='mobile-dock';dock.setAttribute('aria-label','모바일 빠른 메뉴');const items=[['⌂','홈','index.html'],['💌','취향','character.html'],['✨','최애','bias.html']];items.forEach(([icon,label,href])=>{const a=document.createElement('a');a.href=href;a.innerHTML=`<span>${icon}</span><small>${label}</small>`;if(current===href)a.classList.add('active');dock.appendChild(a)});const more=document.createElement('button');more.type='button';more.innerHTML='<span>☰</span><small>전체</small>';more.setAttribute('aria-label','전체 테스트 열기');dock.appendChild(more);document.body.appendChild(dock);const overlay=document.createElement('div');overlay.className='mobile-menu-overlay';overlay.innerHTML=`<div class="mobile-menu-sheet" role="dialog" aria-modal="true" aria-label="전체 테스트"><div class="mobile-sheet-head"><div><b>HEARTVERSE TEST</b><span>7가지 오리지널 남캐 테스트</span></div><button type="button" class="mobile-sheet-close" aria-label="닫기">×</button></div><div class="mobile-test-list">${MOBILE_TESTS.map(([icon,label,href])=>`<a href="${href}" class="${current===href?'active':''}"><span class="mobile-test-icon">${icon}</span><span><b>${label}</b><small>${href==='character.html'?'6문항으로 내 캐릭터 취향 찾기':href==='crush.html'?'답장 속도로 재미용 썸 온도 보기':href==='friendmatch.html'?'친구와 캐릭터 취향 궁합 비교':href==='bias.html'?'오늘 흔들릴 최애캐 세계선 뽑기':href==='danger.html'?'내 취향 패턴 위험도 체크':href==='dateworld.html'?'오늘의 캐릭터 데이트 장면 뽑기':'오리지널 캐릭터에게 한마디 받기'}</small></span><i>›</i></a>`).join('')}</div><div class="mobile-sheet-policy"><a href="about.html">소개</a><a href="contact.html">문의</a><a href="privacy.html">개인정보</a></div></div>`;document.body.appendChild(overlay);const close=()=>{overlay.classList.remove('show');document.body.classList.remove('sheet-open')},open=()=>{overlay.classList.add('show');document.body.classList.add('sheet-open')};more.addEventListener('click',open);overlay.querySelector('.mobile-sheet-close').addEventListener('click',close);overlay.addEventListener('click',e=>{if(e.target===overlay)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}

document.addEventListener('DOMContentLoaded',()=>{applyBranding();fixCharacterArt();$$('.share-btn').forEach(b=>b.addEventListener('click',()=>shareResult(document.title,b.dataset.share||document.body.innerText.slice(0,120))));initMobileNavigation();});